### ISSUE TITLE
[Bug]: can't edit and focus inputs beside the last active one

### ISSUE THREAD

**Issue by T3sT3ro** [corvudev/corvu#45]
### Bug description

I have been redirected here from https://github.com/sek-consulting/solid-ui/issues/115#issuecomment-2233116424

The OTP field should support fixing mistakes and editing individual inputs, but it doesn't. The same issue is marked as "bug" in the shadcn repository. Several other OTP input components from other libraries and frameworks behave as expected — inputs can be navigated with keyboard, tab, mouse and edited as usual. Here, only the last active one can be edited.

### Reproduction Link

https://corvu.dev/docs/primitives/otp-field/

### Reproduction Steps

1. enter 123456
2. try to click/shift-tab/arrow navigate to the input with "3" to correct it to 0
3. You can't, only backspace is allowed and rewriting everything

### Expected behavior

It should be possible to click, focus, tab navigate and navigate with arrow keys to previous inputs and correct previous characters, [similarly to this](https://vuetifyjs.com/en/components/otp-input/#usage)

**Comment by GiyoMoon** [comment]
Hey! While this would be a nice feature, I'm afraid that this is a limitation caused by the way I chose to implement this primitive.
 
Unlike many other implementations, this OTP input renders a single, hidden input, and the slots you see are only visual and can't be interacted with by mouse or touch.

**Comment by T3sT3ro** [comment]
Hello, is there something standing in the way to reconsider another implementation which would be more accessible and more closely follow user expectations?

**Comment by GiyoMoon** [comment]
The current implementation has major advantages compared to a multi-input solution:
- It supports all default input keybindings out of the box as we're working with a single, native input
- Supports copy & paste on all platforms out of the box
- Can retrieve OTP codes from transport (e.g SMS) because we can set `autocomplete='one-timecode'` on the input
- Supports screen readers. They don't get confused by split up inputs
- Password managers work out of the box
- Can easily be controlled from javascript with a single signal

I decided to go with this implementation because the advantages outweighed the drawbacks for me.

**Comment by T3sT3ro** [comment]
Hi, I have noticed today, that in fact navigation is partially possible, however only with keyboard left/right keys. If it works for keyboard left/right, wouldn't it be possible to somehow add support for mouse clicks as well? The focus is managed *almost* properly, with a single difference where delete key moves focus to the previous input field.

**Comment by GiyoMoon** [comment]
Yes, keyboard navigation works without limitations as we have a single input here. The `delete` key moving to the previous field instead of the next is a good catch, I'll have a look if I can fix this.
Mouse clicks don't work with the visual-only slot model we're working with here, it's not related to keyboard navigation working or not.

**Comment by T3sT3ro** [comment]
Maybe it could be possibly to work with [`HTMLInputElement.setSelectionRange()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange) and [`HTMLInputElement.oselectionchange`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/selectionchange_event) with some focus listeners for slots?
