### ISSUE TITLE
[Bug]: When the drawer closes, the scroll position undesirably jumps to the trigger element

### ISSUE THREAD

**Issue by andrerocco** [corvudev/corvu#55]
### Bug description

As it can be noticed on the video demonstration bellow, when a Drawer gets closed, the scroll position of the screen shifts to the Trigger element it is currently positioned somewhere outside the current screen bounds:

https://github.com/user-attachments/assets/b36351a6-d65c-4a97-a705-83e147da331b

In the specific case shown in the video, this behavior isn't a significant issue because, after clicking the Trigger, scrolling the background is disabled, limiting how far the Trigger can shift off-screen. However, this becomes a considerable problem when `modal` is set to `false` and the user can interact with and scroll the screen while the Drawer is open.

### Reproduction Link

https://corvu.dev/docs/primitives/drawer/

### Reproduction Steps

1. Choose a button that triggers a Drawer and shift it out of the screen
2. Activate the button, either by clicking it or, if it is focused, clicking enter
3. Close the drawer

### Expected behavior

There should be no screen shifting after closing a Drawer.

### Additional context

Similar issue a React library: https://github.com/shadcn-ui/ui/issues/2272

**Comment by GiyoMoon** [comment]
Hey, this is expected behavior as we focus back on the trigger when the drawer closes for accessibility reasons.

You have some options if you do not want this to happen in your specific case:
- Set `restoreFocus` to false on the `<Drawer>`. This disables focusing the trigger when the drawer has been closed.
- In the `onFinalFocus` callback on the `<Drawer>`, call `event.preventDefault()` and handle focusing back on the trigger yourself with `preventScroll` set to true. See the [focus() reference on MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#preventscroll).

The drawer inherits these options from the dialog, which is documented [here](https://corvu.dev/docs/primitives/dialog/#Root).

**Comment by andrerocco** [comment]
> Hey, this is expected behavior as we focus back on the trigger when the drawer closes for accessibility reasons.
> 
> 
> 
> You have some options if you do not want this to happen in your specific case:
> 
> - Set `restoreFocus` to false on the `<Drawer>`. This disables focusing the trigger when the drawer has been closed.
> 
> - In the `onFinalFocus` callback on the `<Drawer>`, call `event.preventDefault()` and handle focusing back on the trigger yourself with `preventScroll` set to true. See the [focus() reference on MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#preventscroll).
> 
> 
> 
> The drawer inherits these options from the dialog, which is documented [here](https://corvu.dev/docs/primitives/dialog/#Root).

Ohh, didn't know that, but that makes sense! Nice to know there is a really easy fix.

Thank you @GiyoMoon!!
